### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by jewelc92** [kahrabian/signature_verification#2]
Could you please provide your version of sigwicomp2013 dataset, ie. 'sigwicomp2013.npz' file? I would appreciate if you provide this file, I'm stuck with it for a while, thank you

**Comment by kahrabian** [comment]
I don't have access to the dataset anymore, but the ".npz" file was built from the original dataset. If I remember correctly it was only a simple loading into a numpy array and then saving it.

**Comment by ramithuh** [comment]
If you don't mind i will link this for future readers, (for the .npz files)
https://github.com/anna1995d/signature_verification-1/tree/master/datasets
